package WssCalculator;


/**
* WssCalculator/CalcPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calc.idl
* Monday, October 17, 2016 5:55:57 PM PDT
*/

public abstract class CalcPOA extends org.omg.PortableServer.Servant
 implements WssCalculator.CalcOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("calculate", new java.lang.Integer (0));
    _methods.put ("shutdown", new java.lang.Integer (1));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {

  //Performs the Calculations:ADD/SUB/MUL/DIV
       case 0:  // WssCalculator/Calc/calculate
       {
         int _operator = in.read_long ();
         int num1 = in.read_long ();
         int num2 = in.read_long ();
         int $result = (int)0;
         $result = this.calculate (_operator, num1, num2);
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }


  //The Server EXITS when the Client prompts it to do so
       case 1:  // WssCalculator/Calc/shutdown
       {
         this.shutdown ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:WssCalculator/Calc:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Calc _this() 
  {
    return CalcHelper.narrow(
    super._this_object());
  }

  public Calc _this(org.omg.CORBA.ORB orb) 
  {
    return CalcHelper.narrow(
    super._this_object(orb));
  }


} // class CalcPOA
